#:schema node_modules/wrangler/config-schema.json
name = "twiokk"
main = "src/index.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "twikoo"
database_id = "89af5b62-afac-48df-a357-25af9cb54b9b"
[dev]
port = 5000
